# We shouldnt need anything else than pure python here...
sudo: false
language: python

branches:
  except:
    - gh-pages


env:
  # These will be used to determine the proper version of our dependencies
  # We will NOT rely on a full ROS installation.
  - ROS_DISTRO=indigo
  - ROS_DISTRO=kinetic #TOX_PARAMS="--hypothesis-profile travis"

  # to get latest dependencies (not released in a ROS distro yet)
  - ROS_DISTRO=latest #TOX_PARAMS="--hypothesis-profile travis"


python:
  - 2.7
  # Tests hang !
  #- 3.4

  #- pypy
  #- pypy3

install:
  - pip install tox tox-travis

script:
  - tox

notifications:
  email: false